name: Build Laravel Vendor

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract project ZIP
        run: |
          unzip -q alfaore-store.zip -d extracted

      - name: Show extracted files
        run: |
          ls -la extracted
          ls -la extracted/alfaore-store

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
          extensions: mbstring, bcmath, ctype, fileinfo, openssl, pdo, pdo_mysql, tokenizer, xml

      - name: Install Composer dependencies
        working-directory: extracted/alfaore-store
        env:
          COMPOSER_ALLOW_SUPERUSER: 1
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction

      - name: Create vendor ZIP
        working-directory: extracted/alfaore-store
        run: |
          zip -r vendor.zip vendor

      - name: Upload vendor ZIP
        uses: actions/upload-artifact@v4
        with:
          name: vendor-folder
          path: extracted/alfaore-store/vendor.zip
